### PR TITLE
[MPT-110] Fix Testimonial Carousel

### PR DESCRIPTION
**Pull request by Hackin7**
Initial Issue - Mobile view/ other view bugs out
image

Suspected root cause of the issue is the `isSmall` variable

```
const Index = () => {
  const isSmall = useMediaQuery("(max-width: 800px)");
  const glideRef = useRef(null);
```

When the component is first initialised, the value is ALWAYS false, regardless of orientation. It is then rendered once. This variable is then updated, but the component is not rerendered/ reinitialised after the variable update. The buggy mentor/ mentee listing (and hence offset) would then appear.

The PR initialises the Carousel only AFTER the media query is properly updated (a timeout is a simple enough fix, `useEffect` might be too complicated and interfere with the React Lifecycle). The component would then be rendered with the proper props & styling

Can compare with breakpoint 613 before and after. Before, the carousel overflows. After, the carousel doesn't overflow

Before
image

After
image

This issue took quite a while to debug

### CODE REVIEW

**Comment by Hackin7** [comment]
To fix this rendering issue on resizing

**Comment by Hackin7** [comment]
The issue should be mostly fixed. There is a relatively minor bug when switching from landscape to portrait view (or vice versa), where there is excessive padding at the bottom

image

**Comment by Hackin7** [comment]
There is a relatively minor bug when switching between breakpoints (or vice versa), where there is excessive padding at the bottom (but this bug is quite inconsistent also)

image

However, I can't really consistently recreate it + I think we can spin this off into another issue.
Suspected cause is that react doesn't rerender the components properly on resizing

**Review by wei2912 — APPROVED** [review]
LGTM  - think debouncing is a sufficient fix for this issue, though I'm not sure if 500 ms is enough.

**Pull request merged**
