### PR TITLE
[MPT-12] Resources links table

### PR DESCRIPTION
**Pull request by yashchellani**

### CODE REVIEW

**Comment by yashchellani** [comment]
Preview: 
image

**Comment by wei2912** [comment]
Mobile - stick to current layout
Desktop - arrange in row (or have multiple rows if they don't fit into a single row)

**Review by wei2912 — APPROVED** [review]
LGTM!

**Comment by wei2912** [comment]
Manually merged in https://github.com/AdvisorySG/mentorship-page/commit/2d2a332d5788a76da2f38a759647739d3863a5c7.

**Pull request closed without merging**
