### PR TITLE
 [MPT-33] FAQ: Questions sections hard to see

### PR DESCRIPTION
**Pull request by jeonwonje**
image

use styled api

### CODE REVIEW

**Comment by jeonwonje** [comment]
PR for MPT-33 @wei2912

**Comment by jeonwonje** [comment]
How does this look?
image

**Comment by jeonwonje** [comment]
Tried some other styles too. Personally the yellow rectangle with good margin looks best
image

**Comment by jcc-kh** [comment]
yep I like the white background and yellow outline the best too, also have reviewed the netlify preview, they look good :)

**Review by wei2912 — APPROVED** [review]
LGTM!

**Pull request merged**
