### PR TITLE
[MPT-57] Home: Standardise vertical alignment of content

### PR DESCRIPTION
**Pull request by Unknownflow**
I aligned the headers of the content so they are in line with each other

### CODE REVIEW

**Review by nicholasohjj — CHANGES_REQUESTED** [review]
Vertical alignment fixed.

Mentor tab needs padding and margin from top of the card. Reduce border radius.

Avatar image should be shifted to the left to align with testimonial titles.

More padding between avatar image and right text content.

Consider align left for name + tag, an

d title to align with quote.

**Comment by wei2912** [comment]
To be routed to @jcc-kh for final verdict on design, after @nicholasohjj clarifies feedback above with @Unknownflow.

**Review by wei2912 — CHANGES_REQUESTED** [review]
@Unknownflow See below comment from @jcc-kh:

> Is it possible to have the words 'Managing Director' and 'Persistensie Pte Ltd' on the same line? Right now it's too sparse it looks a bit weird

**Comment by jcc-kh** [comment]
@Unknownflow can attach the updated screenshot of the page here for review

**Comment by Unknownflow** [comment]
image
I have attached the image of the page where the words 'Managing Director' and 'Persistensie Pte Ltd' are on the same line.

**Comment by wei2912** [comment]
Think having them directly side-by-side would impact readability, @jcc-kh do you have suggestions for how they can be arranged on the same line (keeping in mind that the design should work on mobile too)?

**Comment by jcc-kh** [comment]
HM, add a comma in between the words? HAHA I think that's how people do it?
image

**Comment by Unknownflow** [comment]
I have added a comma between the words, in this case it is between the mentor role and company as shown below.

image

**Comment by wei2912** [comment]
Sorry, think I neglected to get this merged in before working on https://github.com/AdvisorySG/mentorship-page/commit/3cd846388737f547a7933d17806068e07f705dfa... will take over the PR.

**Comment by wei2912** [comment]
@Hackin7 Handing over to you in case any of the code here is relevant to the latest version.

**Comment by wei2912** [comment]
Closing PR as it has been superseded by https://github.com/AdvisorySG/mentorship-page/commit/be7f56368238c6cf74d350677bb5217a5f24b664, and was previously made outdated by https://github.com/AdvisorySG/mentorship-page/commit/3cd846388737f547a7933d17806068e07f705dfa.

**Pull request closed without merging**
