### PR TITLE
metatags attempt 1

### PR DESCRIPTION
**Pull request by RyanRTJJ**
inserted a couple metatags for opengraph (facebook) and twitter

### CODE REVIEW

**Comment by bnjmnt4n** [comment]
I think the meta tags should probably be in the HTML file instead of being generated in JavaScript — I don’t think Facebook and Twitter bots have JavaScript activated when scraping them. We can probably use https://cards-dev.twitter.com/validator and https://developers.facebook.com/tools/debug/.

**Comment by wei2912** [comment]
The more powerful spiders might have JavaScript nowadays, since there's headless Chromium, but idk the specifics

**Comment by wei2912** [comment]
How do we test this PR lmao

**Comment by RyanRTJJ** [comment]
I was thinking of just merging and then actually sending the link to see if it works. But it's q a brute force way to test it.

**Comment by wei2912** [comment]
What if you tried sending the deploy link? That might help us prove if it
works.

**Comment by wei2912** [comment]
Just a note, this PR should not be merged at the moment until the `mentorship.advisory.sg` link points to the correct website.

**Comment by bnjmnt4n** [comment]
Maybe we should just merge this now and test. If it doesn‘t work, we can just revert and try static HTML tags instead.

**Comment by wei2912** [comment]
That page is up now and I guess it's worth merging in this anw

**Comment by wei2912** [comment]
Closing, superseded by https://github.com/AdvisorySG/mentorship-page/pull/228.

**Pull request closed without merging**
