### PR TITLE
[MPT-60] New apply button

### PR DESCRIPTION
**Pull request by IvanFengJK**
This is a pull request for the issue [\[MPT-60\]](https://github.com/AdvisorySG/mentorship-page/issues/711) 

I changed the link (`<a>`) element to a button (`<button>`) to make it more appropriate for actions.

Applied a new style to the button to stand out on the page by adding a bold font weight, a subtle shadow and orange for better visual. 

This is the view on the computer:
Screenshot 2024-02-18 at 12 18 34 AM

This is the mobile view:
Screenshot 2024-02-18 at 12 19 08 AM

For ease of reference, I have the styling with the button. Once it's finished. I can move the styling to the CSS file.

### CODE REVIEW

**Review by wei2912 — CHANGES_REQUESTED** [review]
Following Shopify:
image

Think a larger height and padding for the bolded text (while keeping text size the same) would improve the design. Routing to @jcc-kh for further feedback.

**Comment by wei2912** [comment]
Would this be better:

image

(see blue highlighted for changes)

image

**Review by wei2912 — CHANGES_REQUESTED** [review]
See above comment. Also routing to @jcc-kh for review on design.

**Comment by jcc-kh** [comment]
Think the desktop version is fine, the mobile version bugs me a little since the button isn't aligned with the words above (less left margin), not sure if it would be better if it has same amount of left margin as words above it

**Comment by IvanFengJK** [comment]
I have made the changes in green in the web version. I made some changes in the styling for mobile so that it is aligned as shown below.

Screenshot 2024-05-13 at 5 36 29 PM

**Comment by wei2912** [comment]
Merged in https://github.com/AdvisorySG/mentorship-page/commit/8b69b7b449bcc069d4c66496ecaf345644ce5e1a.

**Pull request closed without merging**
