### PR TITLE
[MPT-119] Mentorship 2024 Launch

### PR DESCRIPTION
**Pull request by wei2912**
TODO:
- [x] Merge in https://github.com/AdvisorySG/mentorship-page/pull/787 + FAQ should be vertically aligned (even top/bottom padding)
- [x] Change to yearless logo
- [x] Update partners
- [x] Fix preview image issue
- [x] Switch to 2024 wave
- [x] Apply Now button should look the same between navbar and below
- [x] Apply Now should open in new tab

This PR should be rebased (with `--autosquash`) before merging.

### CODE REVIEW

**Comment by Hackin7** [comment]
LGTM so far, the important (Apply Now) Link is working and Q&A is updated

**Comment by wei2912** [comment]
Deferring merging of https://github.com/AdvisorySG/mentorship-page/pull/787 to @jcc-kh's judgment cos I personally am not sure if I agree with the style choices, and so far nobody has complained about the FAQ text.

**Comment by wei2912** [comment]
Testimonials have been disabled, to be addressed in https://github.com/AdvisorySG/mentorship-page/issues/812.

**Comment by wei2912** [comment]
@Hackin7 would need your help to confirm that 2024 mentors are being loaded after merge.

**Review by Hackin7 — APPROVED** [review]
Generally looks good, though there are a lot of comments that should be settled soon after the Mentorship wave

Mentor loading code looks ok, but I'll merge in and see how

**Pull request merged**
