### PR TITLE
Add link to resume guide

### PR DESCRIPTION
**Pull request by joyceerhl**

### CODE REVIEW

**Comment by wei2912** [comment]
Two quick comments:
1. The link should preferably open in a new tab, you can copy the properties from the link above
2. For files in `public/` we should follow https://create-react-app.dev/docs/using-the-public-folder/

**Comment by joyceerhl** [comment]
> 2. For files in `public/` we should follow https://create-react-app.dev/docs/using-the-public-folder/

Are you referring to not putting this file in `public` if we can help it, or prefixing the path with `process.env.PUBLIC_URL`?

**Comment by wei2912** [comment]
I meant the latter, don't think putting it in `src/` would do any good...

**Comment by joyceerhl** [comment]
OK added, and FWIW I thought you might be suggesting hosting the PDF (and other future assets) on a server (it _is_ >7 megs...)

**Comment by wei2912** [comment]
... wow, okay, should have expected the file sizes to blow up 😂 ah, I'll
work on a proper hosting feature closer to the next time this is done.

**Pull request merged**
