### PR TITLE
[MPT-42] Cards shift left

### PR DESCRIPTION
**Pull request by MatthewYay**
MPT-42 code fix

### CODE REVIEW

**Comment by wei2912** [comment]
To modify `styles/ResultView.css` directly (see https://github.com/AdvisorySG/mentorship-page/blob/master/styles/ResultView.css#L89C23-L90C33) instead of creating a new CSS file that supersedes.

(I'm not sure why there's this superseding behaviour, @Hackin7 do you have any idea?)

**Review by wei2912 — CHANGES_REQUESTED** [review]
See above comment.

**Comment by Hackin7** [comment]
Took a look at this PR, am not too sure how the duplicate file came about tbh.
It seems to me the only issue with this PR is that file, and everything else is solved, so mainly just need to remove the file

Not too up to date on mentorship stuff, but from what I see, the changes here haven't been included in the multi-page branch yet also. So after removing that file this PR should be good to merge in

**Comment by wei2912** [comment]
Manually merged in https://github.com/AdvisorySG/mentorship-page/commit/51ba66de655d0d5552e7513c75b77020c8264069.

**Pull request closed without merging**
